services:
  mysql:
    image: 'mysql:latest'
    container_name: 'integranf_mysql'
    restart: always
    environment:
      - 'MYSQL_DATABASE=integranf'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_container:/data/db
volumes:
  mysql_data_container: