services:
  mysql:
    env_file: ".env"
    image: 'mysql:latest'
    container_name: 'integranf_mysql'
    restart: always
    environment:
      - MYSQL_DATABASE=integranf
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_container:/data/db
volumes:
  mysql_data_container: